<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="style/forXML1.css"?>

<!DOCTYPE store[
<!ELEMENT store (head, product+)>
<!ELEMENT head (id, name, description, price)>
<!ELEMENT product (id, name, description, price)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!-- Объявление сущностей -->
<!ENTITY id_ "ID">
<!ENTITY name_ "NAME">
<!ENTITY description_ "DESCRIPTION">
<!ENTITY price_ "PRICE">
]>

<store>
    <head>
        <id>&id_;</id>
        <name>&name_;</name>
        <description>&description_;</description>
        <price>&price_;</price>
    </head>

     <product>
        <id>1</id>
        <name>Ноутбук</name>
        <description>Мощный ноутбук для работы и игр</description>
        <price>59999</price>
    </product>
    <product>
        <id>2</id>
        <name>Смартфон</name>
        <description>Современный смартфон с отличной камерой</description>
        <price>29999</price>
    </product>
    <product>
        <id>3</id>
        <name>Наушники</name>
        <description>Беспроводные наушники с шумоподавлением</description>
        <price>7999</price>
    </product>
    <product>
        <id>4</id>
        <name>Клавиатура</name>
        <description>Игровая клавиатура с подсветкой</description>
        <price>3499</price>
    </product>
    <product>
        <id>5</id>
        <name>Мышь</name>
        <description>Эргономичная мышь с высоким DPI</description>
        <price>1999</price>
    </product>
</store>